ProyectoFinal/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :aservices
resources :services
resources :rols
resources :userrols
resources :useraservices
resources :users


root 'welcome#index'

end

ProyectoFinal/app/models/useraservice.rb
class Useraservice < ApplicationRecord
end

ProyectoFinal/app/controllers/useraservices_controller.rb
class UseraservicesController < ApplicationController
	before_action :authenticate_user!
	def index
		@useraservices = Useraservice.where(:user_id => current_user.id )
		@services = Service.all
	end
	def new
		@useraservice = Useraservice.new
		@services = Service.all
		
	end
	def show
		@useraservice = Useraservice.find(params[:id])
	end
	def edit
		@useraservice = Useraservice.find(params[:id])
		@services = Service.all
	end
	def destroy
		@useraservice = Useraservice.find(params[:id])
		@useraservice.destroy
		redirect_to useraservices_path
	end
	
	def update
		@useraservice = Useraservice.find(params[:id])
		if @useraservice.update(user_id: current_user.id, service_id: params[:useraservice][:service_id],username: current_user.first_name,password: params[:useraservice][:password], hint: params[:useraservice][:hint])
			redirect_to @useraservice
		else
			render :edit
		end
	end

	def create		
       @useraservice = Useraservice.new(user_id: current_user.id, service_id: params[:useraservice][:service_id],username: current_user.first_name,password: params[:useraservice][:password], hint: params[:useraservice][:hint])
		

		if @useraservice.save
			redirect_to @useraservice
		else
			render :new
		end

	end

	

	private
	
	#def useraservice_params
	#	params.require(:useraservice).permit(:hint,:service_id)
	#+++++++++++++++++++++++++++++++end
#def useraservice_params
#	params.require(:useraservice).permit(:hint,:service_id,:password,:password_confirm)
#end
	

end

ProyectoFinal/app/views/useraservices/_form.html.erb
<%= form_for(@useraservice) do |f| %>
    <% @useraservice.errors.full_messages.each do |message|%>
      <div class="be-red white top-space">
        <%= message %>
      </div>
    <%end%>
    <table>
      <tbody>
        <tr>
          <td>
            <%= f.text_field :hint, placeholder:"Tip para contraseña",class:"form-control" %>
          </td>
        </tr>
        <tr>
          <td>
             <%= f.password_field :password, placeholder:"Contraseña",class:"form-control"%>
          </td>
        </tr>
        <tr>
          <td>
            <%= f.password_field :password_confirm, placeholder:"Confirmar contraseña",class:"form-control" %>
          </td>
        </tr>
        <tr>
          <td>
            <%= f.select :service_id, @services.all.collect{|c| [c.name, c.id]}, prompt: "Selecciona un Servicio",class:"form-control" %>
          </td>
        </tr>
        <tr>
          <td align="center">
            <%= f.submit "Guardar",class:"btn btn-success" %>
            <%= link_to "Cancelar", useraservices_path, class:"btn btn-primary" %>
          </td>
        </tr>
      </tbody>
    </table>
<%end%>
<br><br>
<br><br>
<br><br>
<br><br>

ProyectoFinal/app/views/useraservices/edit.html.erb
<center>
  <h2> Editar configuracion</h2>
  <%= render "form"%>
</center>

ProyectoFinal/app/views/useraservices/index.html.erb
<div class="container">
<center><h2>Servicios con autenticacion especifica </h2></center>
<center> <%= link_to "Nuevan configuracion", new_useraservice_path ,class:"btn btn-primary"%></center>
    <table class="table table-striped">
        <tbody>
        <!-- Aplicadas en las filas -->
	        <tr>
	            <th>id de configuracion</th>
	            <th>id de servicio </th>   
	            <th>nombre de usuario</th>
	            <th></th>
	            <th></th>            
	        </tr>
	         <% cont=0 %>
				<% @useraservices.each do |f| %>
				  <%cont=cont+1%>
				<%end%>
				<% if cont == 0 %>
					<td>
						<p>
							No hay password especiales para algun rervicio
						</p> 
					</td>
				<%else%>
					<% @useraservices.each do |useraservice|%>
						<tr>
							<td><%= useraservice.id %></td>	
							<td><%= @services.find(useraservice.service_id).name  %></td>
							<td><%= useraservice.username %></td>
							<td><%= link_to "Editar", edit_useraservice_path(useraservice),class:"btn btn-primary" %></td>
							<td><%= link_to "Eliminar", useraservice,class:"red", method: :delete, class:"btn btn-danger" %></td>
						</tr>
					<%end%>
				<%end%>
    	</tbody>
    </table>
</div>

<br>
<br><br><br><br><br><br><br>

ProyectoFinal/app/views/useraservices/new.html.erb
<center>
  <h2> Nueva configuracion</h2>
  <%= render "form"%>
</center>


  

ProyectoFinal/app/views/useraservices/show.html.erb
<center>
	<table class="table table-striped">
		<tbody>
			<th>id de servicio</th>
			<th>nombre de usuario</th>
			<th>tip de contraseña</th>
		</tbody>
		<tr>
			<td><%= @useraservice.service_id %></td>
			<td><%= @useraservice.user_id %>  <%= @useraservice.username %></td>
			<td><%= @useraservice.hint %></td>
		</tr>

	</table>
	<%= link_to "Lista de configuracion de servicios", useraservices_path,class:"btn btn-info" %>
</center>

<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>