ProyectoFinal/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :aservices
resources :services
resources :rols
resources :userrols
resources :useraservices
resources :users


root 'welcome#index'

end

ProyectoFinal/app/models/service.rb
class Service < ApplicationRecord
end

ProyectoFinal/app/controllers/services_controller.rb
class ServicesController < ApplicationController
	before_action :authenticate_user!

	def index
		@services = Service.all
	end
	def show
		@service = Service.find(params[:id])
	end
	def new
		@service = Service.new
	end

	def create
		@service = Service.new(service_params)
		if @service.save
		redirect_to @service
		else
			render :new
		end
		
	end
	def destroy
		@service = Service.find(params[:id])
		if @service.destroy
			redirect_to services_path
		else
			@mensaje
		end
	end
	def edit
		@service = Service.find(params[:id])
	end
	def update
		@service = Service.find(params[:id])
		if @service.update(service_params)
			redirect_to @service
		else
			render :edit
		end
	end

	private

	def service_params
		params.require(:service).permit(:name)
	end
end

ProyectoFinal/app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
		<% @service.errors.full_messages.each do |message|%>
			<div class="be-red white top-space">
				<%= message %>
			</div>
		<%end%>
<table>
	<tbody>
		<tr>
			<td>
				<%= f.text_field :name, placeholder: "Nombre del servicio",class:"form-control"%>
			</td>
		</tr>
	</tbody>
</table>
			
			<%= f.submit "Guardar",class:"btn btn-success" %>
			<%= link_to "Cancelar", @service, class:"btn btn-primary" %>
	<%end%>
	<br><br><br><br>
	<br><br><br><br>
	<br><br><br><br>
	

ProyectoFinal/app/views/services/edit.html.erb
<center>
	<h1>Editar servico</h1>
	<%= render "form" %>
</center>

ProyectoFinal/app/views/services/index.html.erb
<div class="container">
<center><h2> Servicios</h2><br>
<%= link_to "Nuevo Rol", new_service_path ,class:"btn btn-primary"%>
</center>

    <table class="table table-striped" align="center">
        <tbody>
        <!-- Aplicadas en las filas -->
	        <tr>
	            <th >Nombre del servicio</th>
	            <th></th>
	            <th></th>           
	        </tr>
			<tr>
				<% @services.each do |service| %>
				<tr>
					<td>
						<%= link_to service.name, service %>	
					</td>
					<td><%= link_to "Editar", edit_service_path(service),class:"btn btn-primary" %></td>
					<td><%= link_to "Eliminar", service,class:"red", method: :delete, class:"btn btn-danger" %></td>
				</tr>
				<%end%>		
    	</tbody>
    </table>
</div>

ProyectoFinal/app/views/services/new.html.erb
<center>
	<h1>Nuevo servico</h1>
	<%= render "form" %>
</center>

ProyectoFinal/app/views/services/show.html.erb
<center>
	<h5>Servicio guardado</h5>
	<h1><%= @service.name %></h1>

<%= link_to "Volver", services_path,class:"btn btn-info" %>
</center>
<br><br><br><br>
	<br><br><br><br>
	<br><br><br><br>