ProyectoFinal/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :aservices
resources :services
resources :rols
resources :userrols
resources :useraservices
resources :users


root 'welcome#index'

end

ProyectoFinal/app/models/rol.rb
class Rol < ApplicationRecord
end

ProyectoFinal/app/controllers/rols_controller.rb
class RolsController < ApplicationController
	before_action :authenticate_user!
	def index
		@rols = Rol.all
	end
	def show
		@rol = Rol.find(params[:id])
	end
	def new
		@rol = Rol.new
	end

	#POST /rols
	def create
		@rol = Rol.new(rol_params)
		
		if @rol.save
			redirect_to @rol
		else
			render :new
		end
	end

	def destroy
		@rol = Rol.find(params[:id])
		@rol.destroy
		redirect_to rols_path
	end

	def edit
		@rol = Rol.find(params[:id])
	end

	def update
		@rol = Rol.find(params[:id])
		if @rol.update(rol_params)
			redirect_to @rol
		else
			render :edit
		end
	end

	private
	
	def rol_params
		params.require(:rol).permit(:name,:code)
	end
end

ProyectoFinal/app/views/rols/_form.html.erb
<%= form_for(@rol) do |f| %>
		<% @rol.errors.full_messages.each do |message|%>
			<div class="be-red white top-space">
				* <%= message %>
			</div>
		<%end%>	
<table>
	<tbody>
		<tr>
			<td>
				<%= f.text_field :name, placeholder: "nombre del rol",class:"form-control" %>
			</td>
		</tr>
		<tr>
			<td>
				<%= f.text_field :code, placeholder: "Codigo",class:"form-control"%>
			</td>
		</tr>
		<tr>
			<td>
				<%= f.submit "Guardar",class:"btn btn-success"%> <%= link_to "Cancelar", rols_path, class:"btn btn-primary" %>
			</td>
		</tr>

	</tbody>

</table>

<%end%>


	<br>
	<br><br><br><br><br><br><br><br><br><br>

ProyectoFinal/app/views/rols/edit.html.erb
<center>
	<h1>Crear nuevo Rol</h1>
	<%= render "form" %>
</center>

ProyectoFinal/app/views/rols/index.html.erb
<div class="container">
<center><h2> Roles</h2></center>
<center> <%= link_to "Nuevo Rol", new_rol_path ,class:"btn btn-primary"%></center>
    <table class="table table-striped">
        <tbody>
        <!-- Aplicadas en las filas -->
	        <tr>
	            <th>Rol</th>
	            <th>Codigo </th>   
	            <th></th>
	            <th></th>            
	        </tr>
	            <% @rols.each do |rol| %>
			<tr>
				<td><%= link_to rol.name, rol %></td>	
				<td><%= rol.code %></td>
				<td><%= link_to "Eliminar", rol, class:"btn btn-danger", method: :delete %></td>
				<td>
					<%= link_to "Editar",edit_rol_path(rol),class:"btn btn-primary" %>
				</td>
				
				
			</tr>
			
		
			<% end %>
    	</tbody>
    </table>
</div>
</div>

ProyectoFinal/app/views/rols/new.html.erb
<center>
	<h1>Crear nuevo Rol</h1>
	<%= render "form" %>
</center>

ProyectoFinal/app/views/rols/show.html.erb
<center><h2> Roles</h2></center>
<center> 
    <table >
        <tbody>
        <!-- Aplicadas en las filas -->
	        <tr>
	            <th>Rol: </th>
	            <td><%= @rol.name%></td>
	                           
	        </tr>
			<tr>
				<th>Codigo: </th>	
				<td><%= @rol.code %></td>
			</tr>
			
    	</tbody>
    </table>
    <br><br>

<div><%= link_to "Lista de Roles", rols_path,class:"btn btn-info" %></div>							

</center>